### ISSUE TITLE
Implement basic interface, table structure and storage

### ISSUE THREAD

**Issue by huhubun** [huhubun/BunBlog.API#24]
- [x] `/posts` Can post blogs (Completed in #26)
- [x] `/tags` Can configuration tags (Completed in #25)
- [x] `/categories` Can configuration categories (Completed in #25)
- [x] Table structure (Completed in #25)
- [x] Save to database (Completed in #26)
